# automatically generated by the FlatBuffers compiler, do not modify

# namespace: kmeans

import flatbuffers

class Packet(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsPacket(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Packet()
        x.Init(buf, n + offset)
        return x

    # Packet
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Packet
    def Duration(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0
    @staticmethod
    def PacketStart(builder): builder.StartObject(1)
    @staticmethod
    def PacketAddDuration(builder, duration): builder.PrependInt32Slot(0, duration, 0)
    @staticmethod
    def PacketEnd(builder): return builder.EndObject()
